language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: build
  keep_history: true
  on:
    branch: master

test:
  - test

after_success:
  - > 
    curl
    -X POST ${WEBHOOK_TELEGRAM}
    -H 'Content-Type: text/plain'
    -H "X-Webhook-Signature: ${WEBHOOK_SIGNATURE}"
    --data-raw $'*TravisCI* success \n*Bello come non mai*'

after_failure:
  - > 
    curl
    -X POST ${WEBHOOK_TELEGRAM}
    -H 'Content-Type: text/plain'
    -H "X-Webhook-Signature: ${WEBHOOK_SIGNATURE}"
    --data-raw $'*TravisCI* failure \n*Brutto come non mai*'
    
    

