language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - curl https://gist.githubusercontent.com/altrdev/9a4fd3b1b1be58a4323d37fd11838b7c/raw/60f0079455ba1ffdcf40002e852253bc1f0c865b/travis_to_thook.sh > travis_to_thook.sh  
  - chmod +x travis_to_thook.sh 
  - export COMMITTER_NAME=$(git log --pretty='%cn' -n1 HEAD)
  - export PROJECT_NAME="altr.dev"
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: build
  keep_history: true
  on:
    branch: master

after_success:
  - ./travis_to_thook.sh -i ${THOOK_ID} -s ${THOOK_SIGNATURE} -p ${PROJECT_NAME} -t success -b ${TRAVIS_BRANCH} -a ${COMMITTER_NAME}

after_failure:
  - ./travis_to_thook.sh -i ${THOOK_ID} -s ${THOOK_SIGNATURE} -p ${PROJECT_NAME} -t failure -b ${TRAVIS_BRANCH} -a ${COMMITTER_NAME}

