language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - export COMMITTER_NAME=$(git log --pretty='%cn' -n1 HEAD)
  - export PROJECT_NAME="altr.dev"
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: build
  keep_history: true
  on:
    branch: master

after_success:
  - ./telegamNotify.sh -w ${WEBHOOK_TELEGRAM} -s ${WEBHOOK_SIGNATURE} -p ${PROJECT_NAME} -r success -b ${TRAVIS_BRANCH} -a ${COMMITTER_NAME}

after_failure:
  - ./telegamNotify.sh -w ${WEBHOOK_TELEGRAM} -s ${WEBHOOK_SIGNATURE} -p ${PROJECT_NAME} -r failure -b ${TRAVIS_BRANCH} -a ${COMMITTER_NAME}
